# General settings
base_url = "https://strangebargain.com"
title = "Strange Bargain"
description = "Thoughts, musings, and information."
author = "Ron Northcutt"
default_language = "en"
minify_html = false
generate_feed = true
feed_filename = "rss.xml"
compile_sass = true
build_search_index = true
output_dir = "docs"

taxonomies = [
        {name = "tags", feed = true}, # each tag will have its own feed
]


[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
render_emoji = true
lazy_async_image = true

[search]
include_title = true
include_description = false
include_path = false
include_content = true
# At which character to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
truncate_content_length = 500
# Accepted value "elasticlunr_javascript" or "elasticlunr_json"
index_format = "elasticlunr_javascript"

[extra]

[extra.papermod]
title = "StrangeBargain"
default_theme = "auto"
theme = "light"
language_direction = "auto"
keywords = ["keyword1", "keyword2", "keyword3"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = false
show_post_nav_links = true
show_post_meta = true
default_toc_open = false
show_post_edit_button = false
edit_post_url = "https://github.com/rlnorthcutt/strangebargain/tree/main"
#copyright = ""
date_format = "%Y-%m-%d"
navigation = [
    { url = "$BASE_URL/archive", title = "Archive" },
    { url = "$BASE_URL/tags", title = "Tags" },
#    { url = "https://getzola.com/", title = "Zola", is_external = true }
]

home_title = "Harmony in Chaos"
home_content = "Welcome to Strange Bargain. This is where we chat about cool tech stuff, business hacks, and what makes our communities tick. If you're into exploring and learning new things, stick around. Let's dive into the fun and weird world together!"
social_icons = [
    { url = "https://www.linkedin.com/in/rlnorthcutt/", title = "LinkedIn", icon = "linkedin" },
    { url = "https://github.com/rlnorthcutt", title = "GitHub", icon = "github" },
    { url = "https://mastodon.social/@rlnorthcutt", title = "Mastodon", icon = "mastodon" },
    { url = "$BASE_URL/rss.xml", title = "RSS", icon = "rss" },
]
